"""
Configuration file generation for Magrathea
"""
from enum import IntEnum
from pathlib import Path
from typing import Dict, Any, Optional


class RunMode(IntEnum):
    """Magrathea run modes"""
    FULL_SOLVER = 0          # Full 4-layer solver with temperature
    ISOTHERMAL = 1           # Temperature-free solver
    TWO_LAYER = 2            # Two-layer mass-radius curves
    BULK_SOLVER = 3          # Bulk input mode with regular solver
    COMPOSITION_FINDER = 4   # Find third layer mass to match M & R
    EOS_MODIFY = 5           # Modify a built-in EOS on the fly
    EOS_ITERATE_TWO_LAYER = 6  # Iterate over EOS modifications with two-layer solver
    EOS_ITERATE_FULL = 7     # Iterate over EOS with regular solver
    MCMC = 8                 # MCMC composition inference


class Config:
    """
    Configuration object for Magrathea runs
    
    Generates configuration files for the C++ Magrathea executable.
    
    Parameters
    ----------
    mode : RunMode or int
        Run mode (0-8)
    output_file : str or Path
        Output file path
    **kwargs
        Additional configuration parameters
        
    Attributes
    ----------
    mode : RunMode
        Run mode
    params : dict
        Configuration parameters
        
    Examples
    --------
    >>> from magrathea import Config, RunMode
    >>> cfg = Config(RunMode.FULL_SOLVER)
    >>> cfg.set('mass_of_core', 0.33)
    >>> cfg.set('mass_of_mantle', 0.67)
    >>> cfg.set('surface_temp', 300)
    >>> cfg.save('myplanet.cfg')
    """
    
    # Default parameters for each run mode
    DEFAULT_PARAMS = {
        'rho_eps_rel': 1e-11,
        'T_eps_rel': 1e-11,
        'ode_eps_rel0': 1e-7,
        'ode_eps_rel1': 1e-10,
        'R_eps_rel': 2e-5,
        'ode_eps_rel2': 1e-10,
        'P_eps_rel': 1e-10,
        'fit_eps_rel': 1e-4,
        'verbose': False,
        'P_surface': 1e5,
        'ave_rho_core': 15,
        'ave_rho_mantle': 5,
        'ave_rho_hydro': 2,
        'ave_rho_atm': 1e-3,
    }
    
    def __init__(self, mode: RunMode = RunMode.FULL_SOLVER, 
                 output_file: str = "./result/Structure.txt", **kwargs):
        self.mode = RunMode(mode)
        self.params: Dict[str, Any] = self.DEFAULT_PARAMS.copy()
        self.params['input_mode'] = int(self.mode)
        self.params['output_file'] = str(output_file)
        
        # Set mode-specific defaults
        if self.mode == RunMode.FULL_SOLVER:
            self.params.update({
                'mass_of_core': 0.0,
                'mass_of_mantle': 0.0,
                'mass_of_hydro': 0.0,
                'mass_of_atm': 0.0,
                'surface_temp': 300,
                'temp_jump_1': 0,
                'temp_jump_2': 0,
                'temp_jump_3': 0,
                'core_phasedgm': 'Fe_default',
                'mantle_phasedgm': 'Si_default',
                'hydro_phasedgm': 'water_default',
                'atm_phasedgm': 'gas_default',
            })
        
        # Update with any provided kwargs
        self.params.update(kwargs)
    
    def set(self, key: str, value: Any) -> None:
        """Set a configuration parameter"""
        self.params[key] = value
    
    def get(self, key: str, default: Any = None) -> Any:
        """Get a configuration parameter"""
        return self.params.get(key, default)
    
    def generate_config_string(self) -> str:
        """Generate configuration file content as string"""
        lines = []
        lines.append("#MAGRATHEA Configuration File")
        lines.append(f"#Generated by Python wrapper (mode {int(self.mode)})")
        lines.append("#" + "=" * 77)
        lines.append("")
        
        # Group parameters by category
        mode_params = []
        global_params = []
        tolerance_params = []
        
        for key, value in self.params.items():
            if key.startswith('mass_of_') or key.startswith('temp_') or key.startswith('surface_') or key == 'input_mode' or key == 'output_file':
                mode_params.append((key, value))
            elif key.endswith('_eps_rel') or key.startswith('fit_'):
                tolerance_params.append((key, value))
            else:
                global_params.append((key, value))
        
        # Write mode parameters
        if mode_params:
            lines.append("#Mode Parameters")
            for key, value in mode_params:
                lines.append(self._format_param(key, value))
            lines.append("")
        
        # Write global parameters
        if global_params:
            lines.append("#Global Run Options")
            for key, value in global_params:
                if not key.endswith('_eps_rel'):
                    lines.append(self._format_param(key, value))
            lines.append("")
        
        # Write tolerance parameters
        if tolerance_params:
            lines.append("#Error Tolerances")
            for key, value in tolerance_params:
                lines.append(self._format_param(key, value))
            lines.append("")
        
        return '\n'.join(lines)
    
    def _format_param(self, key: str, value: Any) -> str:
        """Format a parameter for the config file"""
        if isinstance(value, bool):
            value_str = 'true' if value else 'false'
        elif isinstance(value, str):
            # Quote strings if they contain spaces or special characters
            if ' ' in value or '/' in value or '.' in value:
                value_str = f'"{value}"'
            else:
                value_str = value
        elif isinstance(value, float):
            # Use scientific notation for very small/large values
            if abs(value) < 1e-3 or abs(value) > 1e3:
                value_str = f"{value:.2E}"
            else:
                value_str = str(value)
        else:
            value_str = str(value)
        
        return f"{key}={value_str}"
    
    def save(self, filename: str) -> None:
        """
        Save configuration to a file
        
        Parameters
        ----------
        filename : str
            Path to save the configuration file
        """
        filepath = Path(filename)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        with open(filepath, 'w') as f:
            f.write(self.generate_config_string())
    
    def __str__(self) -> str:
        return self.generate_config_string()
    
    def __repr__(self) -> str:
        return f"Config(mode={self.mode.name}, output_file={self.params.get('output_file')})"
